[theme]
primaryColor = "#7e3abe"
backgroundColor = "#141414"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#ffffff"
font = "sans serif"

[server]
maxUploadSize = 200
enableXsrfProtection = false
enableCORS = false
headless = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501
